general_homepage:
    pattern:  /
    defaults: { _controller: GeneralBundle:General:index }
seccion:
    pattern: /seccion/{name}
    defaults: {_controller: GeneralBundle:General:seccion}
producto:
	pattern: /producto/{name}
    defaults: {_controller: GeneralBundle:General:producto}